In [1]:
import torch
import numpy as np

In [2]:
a_arr = np.array([[1,2,],[3,4,],[5,6],[7,8]])
a_torch = torch.from_numpy(a_arr)

In [3]:
a_arr.ndim

2

In [5]:
a_torch.dim()

2

In [6]:
new_array = a_arr.reshape((2, -1))
new_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
new_tensor = a_torch.view((2,-1))
new_tensor

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [10]:
np.linalg.inv(a_arr[:2,:])

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [13]:
torch.exp(torch.tensor([1,2,3]))

tensor([ 2.7183,  7.3891, 20.0855])